version: "3"

volumes:
  evmapp-forger1-data:
  evmapp-dev1-data:
  evmapp-snark-keys:
  zen-data:
  zcash-params:

networks:
  evmapp_network:
    internal: true
    ipam:
      config:
        - subnet: 10.10.40.0/24
  inet:

services:
  zend:
    image: zencash/zen-node:${ZEN_TAG}
    container_name: zend
    restart: always
    networks:
      evmapp_network:
        ipv4_address: 10.10.40.10
      inet:
    expose:
      - "${ZEN_RPC_PORT}"
      - "${ZEN_WS_PORT}"
    volumes:
      - "zen-data:/mnt/zen:rw"
      - "zcash-params:/mnt/zcash-params:rw"
    environment:
      - "EXTERNAL_IP=${ZEN_EXTERNAL_IP}"
      - "LOCAL_GRP_ID=${ZEN_LOCAL_GRP_ID}"
      - "LOCAL_USER_ID=${ZEN_LOCAL_USER_ID}"
      - "LOG=${ZEN_LOG}"
      - "OPTS=${ZEN_OPTS}"
      - "PORT=${ZEN_PORT}"
      - "RPC_ALLOWIP_PRESET=${ZEN_RPC_ALLOWIP_PRESET}"
      - "RPC_USER=${ZEN_RPC_USER}"
      - "RPC_PASSWORD=${ZEN_RPC_PASSWORD}"
      - "RPC_PORT=${ZEN_RPC_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "4"

  evmapp-forger1:
    image: zencash/evmapp:${SDK_COMMITTISH_EVMAPP}
    container_name: evmapp-forger1
    depends_on:
      - zend
    restart: always
    build:
      context: ./configs/scnode
      dockerfile: Dockerfile_evmapp
      args:
        - "ARG_SDK_VERSION=${SDK_VERSION_EVMAPP}"
        - "SDK_COMMITTISH=${SDK_COMMITTISH_EVMAPP}"
    networks:
      evmapp_network:
        ipv4_address: 10.10.40.2
      inet:
    expose:
      - "${SCNODE_NET_P2P_PORT_FORGER1}"
    ports:
      - 9585:9585
    volumes:
      - "evmapp-forger1-data:/sidechain/datadir:rw"
      - "evmapp-snark-keys:/sidechain/snark_keys:rw"
      - "./logs/evmapp-forger1:/sidechain/logs:rw"
      - "./configs/scnode/evmapp_settings${SCNODE_CONFIG_TEMPLATE_SUFFIX_FORGER}.conf.tmpl:/sidechain/config/sc_settings.conf.tmpl:ro"
    environment:
      - "RPC_USER=${ZEN_RPC_USER}"
      - "RPC_PASSWORD=${ZEN_RPC_PASSWORD}"
      - "RPC_PORT=${ZEN_RPC_PORT}"
      - "LOCAL_GRP_ID=${SCNODE_GRP_ID}"
      - "LOCAL_USER_ID=${SCNODE_USER_ID}"
      - SCNODE_BACKUP_TAR_GZ_URL
      - SCNODE_CERT_MASTERS_PUBKEYS
      - SCNODE_CERT_SIGNERS_MAXPKS
      - SCNODE_CERT_SIGNERS_PUBKEYS
      - "SCNODE_CERT_SIGNERS_SECRETS=${SCNODE_CERT_SIGNERS_SECRETS_FORGER1}"
      - SCNODE_CERT_SIGNERS_THRESHOLD
      - "SCNODE_CERT_SIGNING_ENABLED=${SCNODE_CERT_SIGNING_ENABLED_FORGER}"
      - "SCNODE_CERT_SUBMITTER_ENABLED=${SCNODE_CERT_SUBMITTER_ENABLED_FORGER}"
      - SCNODE_FORGER_ALLOWED_FORGERS
      - "SCNODE_FORGER_ENABLED=${SCNODE_FORGER_ENABLED_FORGER}"
      - SCNODE_FORGER_RESTRICT
      - SCNODE_FORGER_BLOCK_TIME
      - SCNODE_GENESIS_BLOCKHEX
      - SCNODE_GENESIS_SCID
      - SCNODE_GENESIS_POWDATA
      - SCNODE_GENESIS_MCBLOCKHEIGHT
      - SCNODE_GENESIS_MCNETWORK
      - SCNODE_GENESIS_WITHDRAWALEPOCHLENGTH
      - SCNODE_GENESIS_COMMTREEHASH
      - SCNODE_GENESIS_ISNONCEASING
      - SCNODE_NET_KNOWNPEERS
      - SCNODE_NET_MAGICBYTES
      - SCNODE_NET_MAX_IN_CONNECTIONS
      - SCNODE_NET_MAX_OUT_CONNECTIONS
      - "SCNODE_NET_NODENAME=${SCNODE_NET_NODENAME_FORGER1}"
      - "SCNODE_NET_P2P_PORT=${SCNODE_NET_P2P_PORT_FORGER1}"
      - "SCNODE_WALLET_ACCOUNT_ADDRESS=${SCNODE_WALLET_ACCOUNT_ADDRESS_FORGER1}"
      - "SCNODE_WALLET_GENESIS_SECRETS=${SCNODE_WALLET_GENESIS_SECRETS_FORGER1}"
      - SCNODE_WALLET_MAXTX_FEE
      - "SCNODE_WALLET_SEED=${SCNODE_WALLET_SEED_FORGER1}"
      - SCNODE_WS_ZEN_FQDN
      - "SCNODE_WS_ZEN_PORT=${ZEN_WS_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "4"

  evmapp-dev1:
    image: zencash/evmapp:${SDK_COMMITTISH_EVMAPP}
    container_name: evmapp-dev1
    restart: always
    build:
      context: ./configs/scnode
      dockerfile: Dockerfile_evmapp
      args:
        - "ARG_SDK_VERSION=${SDK_VERSION_EVMAPP}"
        - "SDK_COMMITTISH=${SDK_COMMITTISH_EVMAPP}"
    networks:
      evmapp_network:
        ipv4_address: 10.10.40.5
      inet:
    expose:
      - "${SCNODE_NET_P2P_PORT_DEV1}"
    ports:
      - 9545:9545
    volumes:
      - "evmapp-dev1-data:/sidechain/datadir:rw"
      - "evmapp-snark-keys:/sidechain/snark_keys:rw"
      - "./logs/evmapp-dev1:/sidechain/logs:rw"
      - "./configs/scnode/evmapp_settings${SCNODE_CONFIG_TEMPLATE_SUFFIX}.conf.tmpl:/sidechain/config/sc_settings.conf.tmpl:ro"
    environment:
      - "LOCAL_GRP_ID=${SCNODE_GRP_ID}"
      - "LOCAL_USER_ID=${SCNODE_USER_ID}"
      - SCNODE_BACKUP_TAR_GZ_URL
      - SCNODE_CERT_MASTERS_PUBKEYS
      - SCNODE_CERT_SIGNERS_MAXPKS
      - SCNODE_CERT_SIGNERS_PUBKEYS
      - SCNODE_CERT_SIGNERS_THRESHOLD
      - "SCNODE_CERT_SIGNING_ENABLED=${SCNODE_CERT_SIGNING_ENABLED}"
      - "SCNODE_CERT_SUBMITTER_ENABLED=${SCNODE_CERT_SUBMITTER_ENABLED}"
      - SCNODE_FORGER_ALLOWED_FORGERS
      - "SCNODE_FORGER_ENABLED=${SCNODE_FORGER_ENABLED}"
      - SCNODE_FORGER_RESTRICT
      - SCNODE_GENESIS_BLOCKHEX
      - SCNODE_GENESIS_SCID
      - SCNODE_GENESIS_POWDATA
      - SCNODE_GENESIS_MCBLOCKHEIGHT
      - SCNODE_GENESIS_MCNETWORK
      - SCNODE_GENESIS_WITHDRAWALEPOCHLENGTH
      - SCNODE_GENESIS_COMMTREEHASH
      - SCNODE_GENESIS_ISNONCEASING
      - SCNODE_NET_KNOWNPEERS
      - SCNODE_NET_MAGICBYTES
      - SCNODE_NET_MAX_IN_CONNECTIONS
      - SCNODE_NET_MAX_OUT_CONNECTIONS
      - "SCNODE_NET_NODENAME=${SCNODE_NET_NODENAME_DEV1}"
      - "SCNODE_NET_P2P_PORT=${SCNODE_NET_P2P_PORT_DEV1}"
      - "SCNODE_WALLET_ACCOUNT_ADDRESS=${SCNODE_WALLET_ACCOUNT_ADDRESS_DEV1}"
      - "SCNODE_WALLET_GENESIS_SECRETS=${SCNODE_WALLET_GENESIS_SECRETS_DEV1}"
      - SCNODE_WALLET_MAXTX_FEE
      - "SCNODE_WALLET_SEED=${SCNODE_WALLET_SEED_DEV1}"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "4"

  sctool-dev-evm:
    image: zencash/sctool:${SDK_COMMITTISH_SCTOOL}
    container_name: sctool-dev-evm
    restart: "no"
    build:
      context: ./configs/scnode
      dockerfile: Dockerfile_sctool
      args:
        - "ARG_SDK_VERSION=${SDK_VERSION_SCTOOL}"
        - "SDK_COMMITTISH=${SDK_COMMITTISH_SCTOOL}"
    networks:
      evmapp_network:
        ipv4_address: 10.10.40.9
    volumes:
      - "evmapp-snark-keys:/tools/output:rw"
      - "./logs/sctool-dev-evm/sc_bootstrapping_tool.log:/tmp/sc_bootstrapping_tool.log:rw"
    environment:
      - "LOCAL_GRP_ID=${SCNODE_GRP_ID}"
      - "LOCAL_USER_ID=${SCNODE_USER_ID}"
    logging:
      driver: "json-file"
      options:
        max-size: "512m"
        max-file: "4"
